M_time: /home/urbanjs/venus/V600/github/M_CLI/src/M_CLI.f90 File Reference
M_CLI.f90 File Reference
Data Types
type m_cli::option
type m_cli::dictionary
interface m_cli::locate
interface m_cli::insert
interface m_cli::replace
interface m_cli::remove
Modules
module m_cli
Functions/Subroutines
subroutine, public m_cli::check_commandline (ios, message, help_text, version_text)
character(len=:) function, allocatable, public m_cli::commandline (definition, name, noquote)
subroutine, private m_cli::prototype_to_dictionary (string)
subroutine, private m_cli::update (key, val)
subroutine, private m_cli::wipe_dictionary ()
character(len=:) function, allocatable, private m_cli::get (key)
subroutine, private m_cli::prototype_and_cmd_args_to_nlist (prototype, nml)
subroutine m_cli::cmd_args_to_dictionary (check)
subroutine ifnull ()
subroutine m_cli::dictionary_to_namelist (nml)
subroutine, public m_cli::print_dictionary (header, stop)
integer function, private m_cli::longest_command_argument ()
subroutine, private m_cli::locate_c (list, value, place, ier, errmsg)
subroutine, private m_cli::locate_d (list, value, place, ier, errmsg)
subroutine, private m_cli::locate_r (list, value, place, ier, errmsg)
subroutine, private m_cli::locate_i (list, value, place, ier, errmsg)
subroutine, private m_cli::remove_c (list, place)
subroutine, private m_cli::remove_d (list, place)
subroutine, private m_cli::remove_r (list, place)
subroutine, private m_cli::remove_l (list, place)
subroutine, private m_cli::remove_i (list, place)
subroutine, private m_cli::replace_c (list, value, place)
subroutine, private m_cli::replace_d (list, value, place)
subroutine, private m_cli::replace_r (list, value, place)
subroutine, private m_cli::replace_l (list, value, place)
subroutine, private m_cli::replace_i (list, value, place)
subroutine, private m_cli::insert_c (list, value, place)
subroutine, private m_cli::insert_r (list, value, place)
subroutine, private m_cli::insert_d (list, value, place)
subroutine, private m_cli::insert_l (list, value, place)
subroutine, private m_cli::insert_i (list, value, place)
subroutine m_cli::dict_delete (self, key)
character(len=:) function, allocatable m_cli::dict_get (self, key)
subroutine m_cli::dict_add (self, key, value)
pure elemental logical function m_cli::isupper (ch)
elemental pure character(len(str)) function m_cli::upper (str, begin, end)
elemental pure character(len(str)) function m_cli::lower (str, begin, end)
character(len=:) function, allocatable m_cli::quote (str, mode)
character(len=:) function, allocatable m_cli::replace_str (targetline, old, new, ierr, cmd, range)
subroutine m_cli::crack_cmd (cmd, old, new, ierr)
logical function m_cli::strtok (source_string, itoken, token_start, token_end, delimiters)
subroutine m_cli::substitute (targetline, old, new, ierr, start, end)
Variables
character(len=:), dimension(:), allocatable, public m_cli::unnamed
character(len=:), dimension(:), allocatable m_cli::keywords
character(len=:), dimension(:), allocatable m_cli::values
integer, dimension(:), allocatable m_cli::counts
logical, dimension(:), allocatable m_cli::present_in
logical m_cli::keyword_single =.true.
character(len=:), allocatable m_cli::passed_in
character(len=:), allocatable m_cli::g_namelist_name
logical m_cli::g_noquote
logical, public m_cli::debug =.false.
logical m_cli::return_all
Function/Subroutine Documentation
ifnull()
subroutine cmd_args_to_dictionary::ifnull () private
References m_cli::get(), m_cli::update(), and m_cli::upper().