M_CLI: m_cli Module Reference
m_cli Module Reference
Data Types
type dictionary
interface insert
interface locate
type option
interface remove
interface replace
Functions/Subroutines
subroutine, public check_commandline (ios, message, help_text, version_text)
character(len=:) function, allocatable, public commandline (definition, name, noquote)
subroutine, private prototype_to_dictionary (string)
subroutine, private update (key, val)
subroutine, private wipe_dictionary ()
character(len=:) function, allocatable, private get (key)
subroutine, private prototype_and_cmd_args_to_nlist (prototype, nml)
subroutine cmd_args_to_dictionary (check)
subroutine dictionary_to_namelist (nml)
subroutine, public print_dictionary (header, stop)
integer function, private longest_command_argument ()
elemental impure logical function, public specified (key)
subroutine, private locate_c (list, value, place, ier, errmsg)
subroutine, private locate_d (list, value, place, ier, errmsg)
subroutine, private locate_r (list, value, place, ier, errmsg)
subroutine, private locate_i (list, value, place, ier, errmsg)
subroutine, private remove_c (list, place)
subroutine, private remove_d (list, place)
subroutine, private remove_r (list, place)
subroutine, private remove_l (list, place)
subroutine, private remove_i (list, place)
subroutine, private replace_c (list, value, place)
subroutine, private replace_d (list, value, place)
subroutine, private replace_r (list, value, place)
subroutine, private replace_l (list, value, place)
subroutine, private replace_i (list, value, place)
subroutine, private insert_c (list, value, place)
subroutine, private insert_r (list, value, place)
subroutine, private insert_d (list, value, place)
subroutine, private insert_l (list, value, place)
subroutine, private insert_i (list, value, place)
subroutine dict_delete (self, key)
character(len=:) function, allocatable dict_get (self, key)
subroutine dict_add (self, key, value)
pure elemental logical function isupper (ch)
elemental pure character(len(str)) function upper (str, begin, end)
elemental pure character(len(str)) function lower (str, begin, end)
character(len=:) function, allocatable quote (str, mode)
character(len=:) function, allocatable replace_str (targetline, old, new, ierr, cmd, range)
subroutine crack_cmd (cmd, old, new, ierr)
logical function strtok (source_string, itoken, token_start, token_end, delimiters)
subroutine substitute (targetline, old, new, ierr, start, end)
Variables
character(len=:), dimension(:), allocatable, public unnamed
character(len=:), dimension(:), allocatable keywords
character(len=:), dimension(:), allocatable values
integer, dimension(:), allocatable counts
logical, dimension(:), allocatable present_in
logical keyword_single =.true.
character(len=:), allocatable passed_in
character(len=:), allocatable g_namelist_name
logical g_noquote
logical, public debug =.false.
logical return_all
Function/Subroutine Documentation
check_commandline()
subroutine, public m_cli::check_commandline (integer ios, character(len=*) message, character(len=:), dimension(:), intent(in), optional, allocatable help_text, character(len=:), dimension(:), intent(in), optional, allocatable version_text)
References get(), passed_in, and print_dictionary().
cmd_args_to_dictionary()
subroutine m_cli::cmd_args_to_dictionary (logical, intent(in), optional check) private
References debug, g_noquote, get(), ifnull(), keyword_single, keywords, print_dictionary(), quote(), substitute(), unnamed, update(), and upper().
commandline()
character(len=:) function, allocatable, public m_cli::commandline (character(len=*), intent(in) definition, character(len=*), intent(in), optional name, logical, optional noquote)
References g_namelist_name, g_noquote, longest_command_argument(), passed_in, prototype_and_cmd_args_to_nlist(), unnamed, and wipe_dictionary().
crack_cmd()
subroutine m_cli::crack_cmd (character(len=*), intent(in) cmd, character(len=:), intent(out), allocatable old, character(len=:), intent(out), allocatable new, integer ierr) private
References strtok().
dict_add()
subroutine m_cli::dict_add (class(dictionary), intent(inout) self, character(len=*), intent(in) key, character(len=*), intent(in) value) private
dict_delete()
subroutine m_cli::dict_delete (class(dictionary), intent(inout) self, character(len=*), intent(in) key) private
dict_get()
character(len=:) function, allocatable m_cli::dict_get (class(dictionary) self, character(len=*), intent(in) key) private
dictionary_to_namelist()
subroutine m_cli::dictionary_to_namelist (character(len=:), intent(out), allocatable nml) private
References debug, isupper(), keywords, lower(), present_in, return_all, unnamed, and values.
get()
character(len=:) function, allocatable, private m_cli::get (character(len=*), intent(in) key) private
References counts, keywords, and values.
insert_c()
subroutine, private m_cli::insert_c (character(len=:), dimension(:), allocatable list, character(len=*), intent(in) value, integer, intent(in) place) private
References debug.
insert_d()
subroutine, private m_cli::insert_d (doubleprecision, dimension(:), allocatable list, doubleprecision, intent(in) value, integer, intent(in) place) private
References debug.
insert_i()
subroutine, private m_cli::insert_i (integer, dimension(:), allocatable list, integer, intent(in) value, integer, intent(in) place) private
References debug.
insert_l()
subroutine, private m_cli::insert_l (logical, dimension(:), allocatable list, logical, intent(in) value, integer, intent(in) place) private
References debug.
insert_r()
subroutine, private m_cli::insert_r (real, dimension(:), allocatable list, real, intent(in) value, integer, intent(in) place) private
References debug.
isupper()
pure elemental logical function m_cli::isupper (character, intent(in) ch) private
locate_c()
subroutine, private m_cli::locate_c (character(len=:), dimension(:), allocatable list, character(len=*), intent(in) value, integer, intent(out) place, integer, intent(out), optional ier, character(len=*), intent(out), optional errmsg) private
References debug.
locate_d()
subroutine, private m_cli::locate_d (doubleprecision, dimension(:), allocatable list, doubleprecision, intent(in) value, integer, intent(out) place, integer, intent(out), optional ier, character(len=*), intent(out), optional errmsg) private
References debug.
locate_i()
subroutine, private m_cli::locate_i (integer, dimension(:), allocatable list, integer, intent(in) value, integer, intent(out) place, integer, intent(out), optional ier, character(len=*), intent(out), optional errmsg) private
References debug.
locate_r()
subroutine, private m_cli::locate_r (real, dimension(:), allocatable list, real, intent(in) value, integer, intent(out) place, integer, intent(out), optional ier, character(len=*), intent(out), optional errmsg) private
References debug.
longest_command_argument()
integer function, private m_cli::longest_command_argument () private
lower()
elemental pure character(len(str)) function m_cli::lower (character(*), intent(in) str, integer, intent(in), optional begin, integer, intent(in), optional end) private
print_dictionary()
subroutine, public m_cli::print_dictionary (character(len=*), intent(in), optional header, logical, intent(in), optional stop)
References counts, keywords, present_in, unnamed, and values.
prototype_and_cmd_args_to_nlist()
subroutine, private m_cli::prototype_and_cmd_args_to_nlist (character(len=*), intent(in) prototype, character(len=:), intent(out), allocatable nml) private
References cmd_args_to_dictionary(), debug, dictionary_to_namelist(), g_namelist_name, longest_command_argument(), passed_in, present_in, print_dictionary(), prototype_to_dictionary(), return_all, and unnamed.
prototype_to_dictionary()
subroutine, private m_cli::prototype_to_dictionary (character(len=*), intent(in) string) private
References debug, keyword_single, and update().
quote()
character(len=:) function, allocatable m_cli::quote (character(len=*), intent(in) str, character(len=*), intent(in), optional mode) private
References lower(), and replace_str().
remove_c()
subroutine, private m_cli::remove_c (character(len=:), dimension(:), allocatable list, integer, intent(in) place) private
References debug.
remove_d()
subroutine, private m_cli::remove_d (doubleprecision, dimension(:), allocatable list, integer, intent(in) place) private
References debug.
remove_i()
subroutine, private m_cli::remove_i (integer, dimension(:), allocatable list, integer, intent(in) place) private
References debug.
remove_l()
subroutine, private m_cli::remove_l (logical, dimension(:), allocatable list, integer, intent(in) place) private
References debug.
remove_r()
subroutine, private m_cli::remove_r (real, dimension(:), allocatable list, integer, intent(in) place) private
References debug.
replace_c()
subroutine, private m_cli::replace_c (character(len=:), dimension(:), allocatable list, character(len=*), intent(in) value, integer, intent(in) place) private
References debug.
replace_d()
subroutine, private m_cli::replace_d (doubleprecision, dimension(:), allocatable list, doubleprecision, intent(in) value, integer, intent(in) place) private
References debug.
replace_i()
subroutine, private m_cli::replace_i (integer, dimension(:), allocatable list, integer, intent(in) value, integer, intent(in) place) private
References debug.
replace_l()
subroutine, private m_cli::replace_l (logical, dimension(:), allocatable list, logical, intent(in) value, integer, intent(in) place) private
References debug.
replace_r()
subroutine, private m_cli::replace_r (real, dimension(:), allocatable list, real, intent(in) value, integer, intent(in) place) private
References debug.
replace_str()
character(len=:) function, allocatable m_cli::replace_str (character(len=*), intent(in) targetline, character(len=*), intent(in), optional old, character(len=*), intent(in), optional new, integer, intent(out), optional ierr, character(len=*), intent(in), optional cmd, integer, dimension(2), intent(in), optional range) private
References crack_cmd().
specified()
elemental impure logical function, public m_cli::specified (character(len=*), intent(in) key)
References keywords, and present_in.
strtok()
logical function m_cli::strtok (character(len=*), intent(in) source_string, integer, intent(inout) itoken, integer, intent(out) token_start, integer, intent(inout) token_end, character(len=*), intent(in) delimiters) private
substitute()
subroutine m_cli::substitute (character(len=*) targetline, character(len=*), intent(in) old, character(len=*), intent(in) new, integer, intent(out), optional ierr, integer, intent(in), optional start, integer, intent(in), optional end) private
update()
subroutine, private m_cli::update (character(len=*), intent(in) key, character(len=*), intent(in), optional val) private
References counts, debug, keywords, present_in, and values.
upper()
elemental pure character(len(str)) function m_cli::upper (character(*), intent(in) str, integer, intent(in), optional begin, integer, intent(in), optional end) private
wipe_dictionary()
subroutine, private m_cli::wipe_dictionary () private
References counts, keywords, present_in, and values.
Variable Documentation
counts
integer, dimension(:), allocatable m_cli::counts private
debug
logical, public m_cli::debug =.false.
g_namelist_name
character(len=:), allocatable m_cli::g_namelist_name private
g_noquote
logical m_cli::g_noquote private
keyword_single
logical m_cli::keyword_single =.true. private
keywords
character(len=:), dimension(:), allocatable m_cli::keywords private
passed_in
character(len=:), allocatable m_cli::passed_in private
present_in
logical, dimension(:), allocatable m_cli::present_in private
return_all
logical m_cli::return_all private
unnamed
character(len=:), dimension(:), allocatable, public m_cli::unnamed
values
character(len=:), dimension(:), allocatable m_cli::values private