M_time: m_cli::dictionary Type Reference
m_cli::dictionary Type Reference
Private Member Functions
procedure, private get => dict_get
procedure, private set => dict_add
procedure, private del => dict_delete
Private Attributes
character(len=:), dimension(:), allocatable key
character(len=:), dimension(:), allocatable value
integer, dimension(:), allocatable count
Member Function/Subroutine Documentation
del()
procedure, private m_cli::dictionary::del () private
References m_cli::insert_c(), m_cli::insert_d(), m_cli::insert_i(), m_cli::insert_l(), m_cli::insert_r(), m_cli::locate_c(), m_cli::locate_d(), m_cli::locate_i(), m_cli::locate_r(), m_cli::remove_c(), m_cli::remove_d(), m_cli::remove_i(), m_cli::remove_l(), m_cli::remove_r(), m_cli::replace_c(), m_cli::replace_d(), m_cli::replace_i(), m_cli::replace_l(), and m_cli::replace_r().
get()
procedure, private m_cli::dictionary::get () private
set()
procedure, private m_cli::dictionary::set () private
Member Data Documentation
count
integer, dimension(:), allocatable m_cli::dictionary::count private
key
character(len=:), dimension(:), allocatable m_cli::dictionary::key private
value
character(len=:), dimension(:), allocatable m_cli::dictionary::value private
The documentation for this type was generated from the following file:
/home/urbanjs/venus/V600/github/M_CLI/src/M_CLI.f90